# Generated by Django 4.2.1 on 2023-05-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_letter_author_alter_letter_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': [-1]},
        ),
    ]
