# Generated by Django 4.2.1 on 2023-05-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_letter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['date_sended']},
        ),
    ]
