# Generated by Django 4.2.1 on 2023-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_letter_options_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
